### ISSUE TITLE
Very difficult to use

### ISSUE THREAD

**Issue by amigax** [JackJonson/flutter_styled_toast#10]
No proper example of how to use, seems to be tied to one class MyHomePage ? Looks great but I cannot figure out how to use it.

**Comment by JackJonson** [comment]
//Simple use
showToast("hello styled toast");

// Customize toast content widget
showToastWidget(Text('hello styled toast'));

**Comment by Williamtobs** [comment]
> //Simple use showToast("hello styled toast");
> 
> // Customize toast content widget showToastWidget(Text('hello styled toast'));

This still does not explain anything, try do proper documentation of this package
