### ISSUE TITLE
Toast hides when keyboard is active.

### ISSUE THREAD

**Issue by imAunAbbas** [JackJonson/flutter_styled_toast#11]
Hi, I'm using this package, and it is working fine. The only issue I'm facing on both `Android` and `iOS` is that when its `position` is on the `bottom` and the keyboard is active, toast hides behind the keyboard but showing on the `top` `position`.  For now, I'm using it on the top position but it doesn't look so good in my scenario.
Kindly provide any solution to show it at the bottom of the screen without hiding it behind the keyboard. Thanks

**Comment by JackJonson** [comment]
A new version 1.5.0+1 has been released, upgrade flutter_styled_toast to 1.5.0+1.  Setting the parameter 'isHideKeyboard'  true will solve this.
