### ISSUE TITLE
The latest version (v1.5.x) prevents child widgets from getting updated

### ISSUE THREAD

**Issue by hillelcoren** [JackJonson/flutter_styled_toast#12]
Hi, thanks for the very helpful package! 

Since updating from v1.4.x to v1.5.x I'm no longer able to force the child widgets to update. 

This is the approach I'm using which could definitely be part of the problem: 

https://hillel.dev/2018/08/15/flutter-how-to-rebuild-the-entire-app-to-change-the-theme-or-locale/

Any thoughts?

**Comment by JackJonson** [comment]
A new version 1.5.1+1 has been released. Upgrading flutter_styled_toast to 1.5.1+1 should solve this problem.

**Comment by hillelcoren** [comment]
Works great, thank you!!
