### ISSUE TITLE
How to hide the toast ?

### ISSUE THREAD

**Issue by MahmoudAbunaji** [JackJonson/flutter_styled_toast#19]
How to hide the shown toast programmatically

**Comment by ApoorvaMysoreNataraja** [comment]
There's no neat way to do that. I found that specifying isIgnoring and duration parameters works. If you want a toast to stay forever you could do :
```
showToastWidget(
    isIgnoring: false
    duration: Duration.zero
)
```
If you want this same toast to be dismissed :
```
showToastWidget(
    isIgnoring: true
    duration: Duration(milliseconds: 1)
)
```

**Comment by JackJonson** [comment]
Use `dismissAllToast(showAnim: true);`

**Comment by MahmoudAbunaji** [comment]
@JackJonson I'll try thank you
