### ISSUE TITLE
Getting issue on flutter version 3.0.0

### ISSUE THREAD

**Issue by krButani** [JackJonson/flutter_styled_toast#23]
/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_styled_toast-2.0.0/lib/src/styled_toast.dart:1559:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/G:/AAAInstallation/src/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);

**Comment by JackJonson** [comment]
New version 2.1.2 has been released.

**Comment by Shanoobmk** [comment]
this issue not solved

**Comment by Tanyangfan** [comment]
I meet same issue

**Comment by ehsan097** [comment]
The issue is not resolved yet.

**Comment by utkarsh-karnik** [comment]
This issue is still not resolved yet.

**Comment by lozthiensu** [comment]
This issue is still not resloved yet
