### ISSUE TITLE
error when build in ios

### ISSUE THREAD

**Issue by eggysudianto** [JackJonson/flutter_styled_toast#25]
Showing All Messages
../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_styled_toast-2.1.3/lib/src/styled_toast.dart:497:63: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null

flutter 2.10.5
dart 2.16.2

**Comment by JackJonson** [comment]
Upgrading to flutter 3.0.0.

**Comment by JackJonson** [comment]
@Urvish24  flutter_styled_toast: ^2.0.0

**Comment by juniorbomb** [comment]
> @Urvish24 flutter_styled_toast: ^2.0.0

`flutter_styled_toast: 2.0.0`
Works for me
