### ISSUE TITLE
When I scope flutter_styled_toast in flutter >=3.10.1, viewInsects in MediaQuery don't work.

### ISSUE THREAD

**Issue by oboard** [JackJonson/flutter_styled_toast#29]
When I scope flutter_styled_toast in flutter >=3.10.1, viewInsects in MediaQuery don't work.
Especially when a TextField on the bottom of my screen and I click the TextField, view wouldn't resize in time

**Comment by gabrielguedest** [comment]
I have opened a pull request that fixes this issue:
https://github.com/JackJonson/flutter_styled_toast/pull/30

If you would like to use the fix, you can update the dependency in your pubspec.yaml file to point directly to the branch with the fix until the pull request is approved:
`
flutter_styled_toast:
  git:
    url: https://github.com/gabrielguedest/flutter_styled_toast
    ref: master
`

**Comment by darkstarx** [comment]
Have the same trouble. All text fields don't scroll up when the virtual keyboard is opening.
I can confirm the PR #30 is working for this moment, I'd be appreciate the maintainer for merging.

**Comment by JackJonson** [comment]
New version 2.2.1 published which upgraded to 3.10.x
