### ISSUE TITLE
Request: Allow widget to slide from the edge of the screen with no gap

### ISSUE THREAD

**Issue by volgin** [JackJonson/flutter_styled_toast#6]
It will be nice to be able to slide a toast from the edge of the screen, and keep it connected to that edge with no gap.

In my design a toast takes full width of a screen, and it looks better with no gap, especially on devices with rounded corners, e.g. iPhone 11.

**Comment by JackJonson** [comment]
> It will be nice to be able to slide a toast from the edge of the screen, and keep it connected to that edge with no gap.
> 
> In my design a toast takes full width of a screen, and it looks better with no gap, especially on devices with rounded corners, e.g. iPhone 11.

We will consider development in subsequent versions

**Comment by JackJonson** [comment]
> It will be nice to be able to slide a toast from the edge of the screen, and keep it connected to that edge with no gap.
> 
> In my design a toast takes full width of a screen, and it looks better with no gap, especially on devices with rounded corners, e.g. iPhone 11.

The example in latest version 1.3.0  shows how to customize toast widget to make it no gap from the screen. 
https://github.com/JackJonson/flutter_styled_toast/blob/master/example/lib/main.dart 
start line 549 shows how to do.
